### PR TITLE
Update breadcrumbs on profile name update

### PR DESCRIPTION
**Pull request by Rayn322**
Previously didn't update until you leave and go back into the profile page

### CODE REVIEW

**Review by CodexAdrian — APPROVED** [review]
LGTM

**Review by Geometrically — APPROVED** [review]

**Comment by Geometrically** [comment]
pls resolve conflicts + update branch

**Comment by Rayn322** [comment]
uh something went wrong lmao

**Comment by Rayn322** [comment]
I really need to learn rebases and merges better but that looks like it works

**Review by Geometrically — APPROVED** [review]

**Pull request merged**
