### PR TITLE
TypeScript

### PR DESCRIPTION
**Pull request by RedstoneWizard08**
Just moving the existing JS code into TypeScript. This should be working fairly well.

Note: I do most dev on my chromebook, so that's why there's "Web" things.

### CODE REVIEW

**Comment by RedstoneWizard08** [comment]
Update: I gotta do some tests before I remove the draft label, so it may be a few days.

**Comment by TheoCGaming** [comment]
a few days

**Comment by RedstoneWizard08** [comment]
Yea lol I've been busy with other stuff and haven't been working on this in a while, prob should get back on this soon

**Comment by triphora** [comment]
We appreciate the idea, but this will conflict with so many things, especially while the app is still in the middle of development. If you are going to make PRs, please consult with folks on Discord first and only make incremental changes.

**Pull request closed without merging**
