### PR TITLE
Based on issue #831

### PR DESCRIPTION
**Pull request by MrLiam2614**
Added "Update" button on the instance of the ModPack Card.
immagine
The ModPack instances inside the "Home Page"

immagine
The ModPack instances inside the "Library"

immagine
When you click the "Update" button it automatically open the ModPack Content and directly the "Change Version" so you can Update it

### CODE REVIEW

**Comment by Geometrically** [comment]
feature is not needed in the launcher, there are already ways to update a pack

**Comment by MrLiam2614** [comment]
> feature is not needed in the launcher, there are already ways to update a pack

My addition was designed because, since you can start the profile directly by hovering over it, many users don't even see that there are updates; when they open modrinth they want to start the game immediately.
However it's your choice, absolutely no problem ^^

**Comment by BumbleTree** [comment]
Trust me, This is ESSENTIAL, for packs that are required for a server. Hard enough getting people to install modrinth. A clear update button like this is a massive improvement over the embedded nature of the update feature that isnt  instantly clear to anyone using it for the first time

**Comment by MrLiam2614** [comment]
I hope you will revaluate this feature cause A LOT of players on public server are having issues when they have to update the server modpack. They just open modrinth and start the modpack, without opening it, so we got tens of users in the support section asking "why can't i play!" when the only thing they need to do is updating.
Peoples are lazy so if you give them an immediate and visible feedback that there is an update it would be a lot better

**Comment by blryface** [comment]
This seems like it may be an useful addition, but I think people will still go right trough it and complain anyways

**Pull request closed without merging**
