### PR TITLE
Update README formatting, add screenshot of the GUI

### PR DESCRIPTION
**Pull request by SkyfallWasTaken**

### CODE REVIEW

**Comment by wafflecoffee** [comment]
I don't think any of this is needed. The formatting is good as-is, and the GUI is nowhere near finished.

**Comment by SkyfallWasTaken** [comment]
> the GUI is nowhere near finished

While that may be true, it'd be nice to have a screenshot of the UI as it is right now, even if said UI is incomplete.

**Comment by pauliesnug** [comment]
Yeah there doesn't seem to be a need for this at all, especially seeing as hacktoberfest ended a while ago.

**Comment by SkyfallWasTaken** [comment]
Your choice, but what does Hacktoberfest got to do with anything?

**Comment by triphora** [comment]
I would ignore that part. It's a joke about the fact that people often make (usually unwanted or inconsequential) pull requests to README files during the month of October to fill up their Hacktoberfest quota without having to actually do any code.

**Comment by SkyfallWasTaken** [comment]
> I would ignore that part. It's a joke about the fact that people often make (usually unwanted or inconsequential) pull requests to README files during the month of October to fill up their Hacktoberfest quota without having to actually do any code.

That explains it, thank you!

**Pull request closed without merging**
