### PR TITLE
Move launcher working directory to standard location

### PR DESCRIPTION
**Pull request by enderger**
This changes the launcher working directory to be in a standard location and fixes a bug with nonexistent launcher data.

### CODE REVIEW

**Review by Geometrically — CHANGES_REQUESTED** [review]
Looks good, but can there be a development mode which saves to a directory inside the project? Would make debugging easier and if a developer had a real theseus install, it wouldn't mess stuff up

**Comment by Code-Ac** [comment]
Maybe set it so that if either it isn't able to create the config file or there is an override option set in the config, it chooses respectively the current working directory or the path set as override.

**Comment by CatDevz** [comment]
> Looks good, but can there be a development mode which saves to a directory inside the project? Would make debugging easier and if a developer had a real theseus install, it wouldn't mess stuff up

An environment variable like `THESEUS_PATH` could be a nice way to control this.

**Comment by enderger** [comment]
I've added an environment variable for the settings path.

**Review by Geometrically — APPROVED** [review]

**Pull request merged**
